

services:
  app:
    build: .
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - DB_CONNECTION=mongodb
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_DATABASE=Project0

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: